### PR TITLE
Adding dbt-beyond-the-basics

### PR DESCRIPTION
**Pull request by pgoslatara**
Adding [dbt-beyond-the-basics](https://github.com/pgoslatara/dbt-beyond-the-basics), a dbt project I maintain that showcases some advanced features that can be used in CI for dbt projects and contains an extensive README that details these features.

### CODE REVIEW

**Comment by zsombor-flds** [comment]
Hey @pgoslatara,

This seems like a duplicate for me.
Let me know if you have any questions otherwise I will close this PR.

**Comment by pgoslatara** [comment]
> Hey @pgoslatara,
> 
> This seems like a duplicate for me. Let me know if you have any questions otherwise I will close this PR.

@zsombor-flds Is it possible to add the same repo to two sections? Currently my repo is in the "Sample Projects" section when I feel the "CI/CD" section is far more appropriate. Would be nice to be in both rather than having to remove it from the initial section.

**Comment by zsombor-flds** [comment]
I would prefer to keep one entry per resource. However, if you want, you can move it from Samples to CI/CD.

Thanks!

**Comment by pgoslatara** [comment]
@zsombor-flds Done!

**Comment by zsombor-flds** [comment]
TY @pgoslatara !

**Pull request merged**
